# Top-level Makefile
# Builds everything: planet, Python interface and CLI interface

CC     = /usr/lib/ggdb
CFLAGS = -Wall -fPIC -std=c++11 -Ilib -Iplanet -Itinyxml2 -fopenmp -MMD -MP


# Common files for the shared lib (libatjup.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATJUP_OBJ = planet/cJupiterModel.o planet/PrintMsg_Jup.o planet/RungeKutta_Jup_Turb.o \
planet/RHS_Jup_Turb.o planet/ParaView_Jup.o planet/Thermo_Jup.o \
planet/InitValues_Jup.o planet/SaturationAdjustmentJup.o planet/ThermalWindJup.o \
planet/FileIO_Jup.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATJUP_CLI_OBJ = cli/jup.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = planet/cJupiterDefaults.cpp.inc planet/JupiterLoadConfig.cpp.inc \
planet/JupiterParams.h.inc jupiter/config_atjup.xml python/jupiter_pxd.pxi python/pyatjup.pyx

#copy pyatjup.so from python dir to jupiter dir
COPY_FILE = pyatjup.so
TARGET_DIR = jupiter

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: jup python $(target)

libatjup.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATJUP_OBJ) $(XML_OBJ)
	ar rcs libatjup.a $(LIB_OBJ) $(ATJUP_OBJ) $(XML_OBJ)

jup: libatjup.a $(ATJUP_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATJUP_CLI_OBJ) -L. -latjup $(LDFLAGS) -o cli/jup

$(PARAM_OUTPUTS): param.py
# explicitly clean dependent files
	rm -f planet/cJupiterModel.o
	python3 param.py

analyze:
	analyze-build make

python: libatjup.a python/pyatjup.so

python/pyatjup.so: python/pyatjup.pyx python/atjup.pxd libatjup.a
	cd python && python3 setup.py build_ext --inplace

# copy pyatjup.so from python dir to jupiter dir
$(TARGET_DIR)/pyatjup.so: python/pyatjup.cpython-310-x86_64-linux-gnu.so
	cp $< $@


planet/%.o: planet/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

# Auto-generated header dependency files (produced by -MMD -MP)
ALL_DEPS = $(LIB_OBJ:.o=.d) $(ATJUP_OBJ:.o=.d) $(XML_OBJ:.o=.d) $(ATJUP_CLI_OBJ:.o=.d)
-include $(ALL_DEPS)

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATJUP_OBJ) $(XML_OBJ) $(ATJUP_CLI_OBJ) $(PARAM_OUTPUTS) jup libatjup.a $(ALL_DEPS)
	\rm -vf python/*.so python/*.o python/pyatjup.cpp
	\rm -rf python/build/

# Verify the shared physics headers have not diverged between the planet models.
.PHONY: check-shared
check-shared:
	@grep -v '^#' planet/SHARED.md5 | md5sum -c - && echo "shared headers OK"
