# pxi files
# THIS FILE IS AUTOMATICALLY GENERATED BY param.py
# ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME
import sys

from atjup cimport cJupiterModel

from libcpp cimport bool
from libcpp.string cimport string
from libcpp.vector cimport vector

class Model:
    """
        ATJUP Jupiter's cell structure in the atmosphere
    """
    def __init__(self):
        self.jupiter = Jupiter()
        self.output_path = ""
        self.config_xml = ""

    def run_atjup(self, output_path, cfg_xml):
        self.output_path = output_path
        self.config_xml = cfg_xml

#        cfg_xml = cfg_xml.str.encode('utf-8')

        print self.output_path 
        print self.config_xml 
        self.jupiter.load_config(self.config_xml)
        self.jupiter.run()




cdef class Jupiter:
    """ 
    Cython wrapper class for C++ class Jupiter
    """
    cdef:
        cJupiterModel *_thisptr

    def __cinit__(Jupiter self):
        # Initialize the "this pointer" to NULL so __dealloc__
        # knows if there is something to deallocate. Do not 
        # call new cJupiterModel() here.
        self._thisptr = NULL
        
    def __init__(Jupiter self):
        # Constructing the C++ object might raise std::bad_alloc
        # which is automatically converted to a Python MemoryError
        # by Cython. We therefore need to call "new cJupiterModel()" in
        # __init__ instead of __cinit__.
        self._thisptr = new cJupiterModel() 

    def __dealloc__(Jupiter self):
        # Only call del if the C++ object is alive, 
        # or we will get a segfault.
        if self._thisptr != NULL:
            del self._thisptr
            
    cdef int _check_alive(Jupiter self) except -1:
        # Because of the context manager protocol, the C++ object
        # might die before PyJupiter self is reclaimed.
        # We therefore need a small utility to check for the
        # availability of self._thisptr
        if self._thisptr == NULL:
            raise RuntimeError("Wrapped C++ object is deleted")
        else:
            return 0

    def load_config(Jupiter self, str filename):
        self._check_alive()
        self._thisptr.LoadConfig(filename)
        return None

    def run(Jupiter self):
        self._check_alive()
        self._thisptr.Run()
        return None

    # common section
    property verbose:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.verbose
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.verbose = <bool> value
    
    property output_path:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.output_path
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.output_path = <string> value
    
    property paraview_panorama_vts_flag:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.paraview_panorama_vts_flag
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.paraview_panorama_vts_flag = <bool> value
    
    # jupiter section
    property nm:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.nm
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.nm = <int> value
    
    property checkpoint:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.checkpoint
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.checkpoint = <int> value
    
    property panorama_print:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.panorama_print
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.panorama_print = <int> value
    
    property Coriolis:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.Coriolis
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.Coriolis = <double> value
    
    property centrifugal:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.centrifugal
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.centrifugal = <double> value
    
    property buoyancy:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.buoyancy
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.buoyancy = <double> value
    
    property chemical_reaction:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.chemical_reaction
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.chemical_reaction = <double> value
    
    property coord_stretching:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.coord_stretching
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.coord_stretching = <bool> value
    
    property L_atm:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.L_atm
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.L_atm = <double> value
    
    property tropopause_pole:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.tropopause_pole
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.tropopause_pole = <double> value
    
    property tropopause_equator:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.tropopause_equator
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.tropopause_equator = <double> value
    
    property re:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.re
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.re = <double> value
    
    property ec:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ec
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ec = <double> value
    
    property ep:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ep
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ep = <double> value
    
    property hp:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.hp
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.hp = <double> value
    
    property lv:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.lv
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.lv = <double> value
    
    property ls:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ls
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ls = <double> value
    
    property cp_l:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.cp_l
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.cp_l = <double> value
    
    property pr:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.pr
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.pr = <double> value
    
    property g:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.g
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.g = <double> value
    
    property omega:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.omega
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.omega = <double> value
    
    property gam:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.gam
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.gam = <double> value
    
    property u_0:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.u_0
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.u_0 = <double> value
    
    property r_0_water:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.r_0_water
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.r_0_water = <double> value
    
    property ua:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ua
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ua = <double> value
    
    property va:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.va
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.va = <double> value
    
    property wa:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.wa
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.wa = <double> value
    
    property pa:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.pa
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.pa = <double> value
    
    property ca:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ca
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ca = <double> value
    
    property ta:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ta
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ta = <double> value
    
    property t_ref:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.t_ref
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.t_ref = <double> value
    
    property t_equator:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.t_equator
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.t_equator = <double> value
    
    property t_pole:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.t_pole
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.t_pole = <double> value
    
    property p_ref:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.p_ref
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.p_ref = <double> value
    
    property R_ref:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.R_ref
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.R_ref = <double> value
    
    property t_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.t_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.t_tropopause = <double> value
    
    property t_react_onset:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.t_react_onset
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.t_react_onset = <double> value
    
    property p_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.p_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.p_tropopause = <double> value
    
    property h2_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.h2_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.h2_tropopause = <double> value
    
    property he_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.he_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.he_tropopause = <double> value
    
    property h2o_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.h2o_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.h2o_tropopause = <double> value
    
    property h2s_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.h2s_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.h2s_tropopause = <double> value
    
    property nh3_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.nh3_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.nh3_tropopause = <double> value
    
    property nh4sh_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.nh4sh_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.nh4sh_tropopause = <double> value
    
    property ch4_tropopause:
        def __get__(Jupiter self):
            self._check_alive()
            return self._thisptr.ch4_tropopause
    
        def __set__(Jupiter self, value):
            self._check_alive()
            self._thisptr.ch4_tropopause = <double> value
    


    # The context manager protocol allows us to precisely
    # control the liftetime of the wrapped C++ object. del
    # is called deterministically and independently of 
    # the Python garbage collection.

    def __enter__(Jupiter self):
        self._check_alive()
        return self
    
    def __exit__(Jupiter self, exc_tp, exc_val, exc_tb):
        if self._thisptr != NULL:
            del self._thisptr 
            self._thisptr = NULL # inform __dealloc__
        return False # propagate exceptions

cdef public void PythonPrint(const char *s):
    print s,
    sys.stdout.flush()
